spring:
  application:
    name: TrueToYourShelf
  jackson:
    mapper:
      defaultViewInclusion: true
    default-property-inclusion: NON_NULL

dictionary:
  url: https://dictionaryapi.com

library:
  url: https://api.dp.la